{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "paywallet.fullname" . }}
  labels:
    {{- include "paywallet.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "paywallet.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: management
      path: /actuator/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
