-- Data keys generated by KMS, stored only encrypted under the master key. DATA keys encrypt fields and rotate;
-- the INDEX key computes blind indexes and must not change, or every index would have to be recomputed.
CREATE TABLE encryption_keys (
    id             VARCHAR(16)              PRIMARY KEY,
    purpose        VARCHAR(5)               NOT NULL,
    encrypted_key  TEXT                     NOT NULL,
    active         BOOLEAN                  NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_encryption_keys_purpose CHECK (purpose IN ('DATA', 'INDEX'))
);

CREATE UNIQUE INDEX ux_encryption_keys_active ON encryption_keys (purpose) WHERE active;

-- CPF/CNPJ and phone numbers are stored encrypted; lookups and uniqueness use a keyed hash (blind index).
-- The index columns are filled when the application encrypts existing rows on startup.
ALTER TABLE users DROP CONSTRAINT ck_users_document;
ALTER TABLE users DROP CONSTRAINT users_document_key;
ALTER TABLE users ALTER COLUMN document TYPE VARCHAR(255);
ALTER TABLE users ADD COLUMN document_index VARCHAR(64) UNIQUE;

ALTER TABLE pix_keys DROP CONSTRAINT pix_keys_key_value_key;
ALTER TABLE pix_keys ALTER COLUMN key_value TYPE VARCHAR(255);
ALTER TABLE pix_keys ADD COLUMN value_index VARCHAR(64) UNIQUE;

ALTER TABLE pix_payments ALTER COLUMN key_value TYPE VARCHAR(255);
ALTER TABLE marketplace_orders ALTER COLUMN phone_number TYPE VARCHAR(255);
