CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(255)             NOT NULL,
    document    VARCHAR(14)              NOT NULL UNIQUE,
    email       VARCHAR(255)             NOT NULL UNIQUE,
    password    VARCHAR(255)             NOT NULL,
    type        VARCHAR(20)              NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_users_type CHECK (type IN ('COMMON', 'MERCHANT')),
    CONSTRAINT ck_users_document CHECK (document ~ '^[0-9]{11}$|^[0-9]{14}$')
);
