package br.com.paywallet.crypto;

import java.sql.Timestamp;
import java.time.Clock;
import java.time.Instant;
import java.util.Base64;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import javax.sql.DataSource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.stereotype.Component;
import org.springframework.transaction.support.TransactionTemplate;

import software.amazon.awssdk.core.SdkBytes;
import software.amazon.awssdk.services.kms.KmsClient;
import software.amazon.awssdk.services.kms.model.DataKeySpec;
import software.amazon.awssdk.services.kms.model.NotFoundException;

/**
 * Envelope encryption: data keys are generated by KMS, used in memory and stored only encrypted under the KMS master
 * key, so the database alone never reveals them. Every ciphertext names its key, which keeps old data readable
 * after a rotation.
 */
@Component
public class KeyRing {

    public record KeyInfo(String id, String purpose, boolean active, Instant createdAt) {
    }

    private record StoredKey(String id, String purpose, String encryptedKey, boolean active) {
    }

    private static final Logger log = LoggerFactory.getLogger(KeyRing.class);
    private static final String DATA = "DATA";
    private static final String INDEX = "INDEX";

    private final JdbcTemplate jdbc;
    private final KmsClient kms;
    private final CryptoProperties props;
    private final TransactionTemplate transactions;
    private final Clock clock;
    private final Map<String, SecretKey> keys = new ConcurrentHashMap<>();
    private volatile boolean loaded;
    private volatile String activeDataKeyId;
    private volatile SecretKey indexKey;

    /**
     * Hibernate creates the field converters, and with them this class, while the entity manager is still being
     * built: nothing here may depend on JPA, and KMS and the key table are only touched on first use.
     */
    KeyRing(JdbcTemplate jdbc, DataSource dataSource, KmsClient kms, CryptoProperties props, Clock clock) {
        this.jdbc = jdbc;
        this.kms = kms;
        this.props = props;
        this.transactions = new TransactionTemplate(new DataSourceTransactionManager(dataSource));
        this.clock = clock;
    }

    String activeDataKeyId() {
        ensureLoaded();
        return activeDataKeyId;
    }

    SecretKey dataKey(String id) {
        ensureLoaded();
        SecretKey key = keys.get(id);
        if (key == null) {
            reload();
            key = keys.get(id);
        }
        if (key == null) {
            throw new IllegalStateException("Unknown data key " + id);
        }
        return key;
    }

    SecretKey indexKey() {
        ensureLoaded();
        return indexKey;
    }

    /** New data is encrypted with a new key from now on; existing ciphertexts keep working with their own key. */
    public KeyInfo rotateDataKey() {
        ensureLoaded();
        String id = transactions.execute(status -> {
            jdbc.update("UPDATE encryption_keys SET active = FALSE WHERE purpose = ? AND active", DATA);
            return insertNewKey(DATA);
        });
        reload();
        log.info("Data key rotated: {} is now active", id);
        return keys().stream().filter(k -> k.id().equals(id)).findFirst().orElseThrow();
    }

    public List<KeyInfo> keys() {
        return jdbc.query("SELECT id, purpose, active, created_at FROM encryption_keys ORDER BY created_at",
                (rs, i) -> new KeyInfo(rs.getString(1), rs.getString(2), rs.getBoolean(3),
                        rs.getTimestamp(4).toInstant()));
    }

    private synchronized void ensureLoaded() {
        if (loaded) {
            return;
        }
        ensureMasterKey();
        ensureActiveKey(DATA);
        ensureActiveKey(INDEX);
        reload();
        loaded = true;
    }

    private void ensureMasterKey() {
        if (!props.createMasterKey()) {
            return;
        }
        try {
            kms.describeKey(r -> r.keyId(props.masterKeyAlias()));
        } catch (NotFoundException e) {
            String keyId = kms.createKey(r -> r.description("PayWallet PII master key")).keyMetadata().keyId();
            kms.createAlias(r -> r.aliasName(props.masterKeyAlias()).targetKeyId(keyId));
            log.warn("Created KMS master key {} ({}); development only", props.masterKeyAlias(), keyId);
        }
    }

    private void ensureActiveKey(String purpose) {
        Integer active = jdbc.queryForObject("SELECT count(*) FROM encryption_keys WHERE purpose = ? AND active",
                Integer.class, purpose);
        if (active != null && active > 0) {
            return;
        }
        try {
            insertNewKey(purpose);
        } catch (DuplicateKeyException e) {
            log.info("{} key created by another instance", purpose);
        }
    }

    private String insertNewKey(String purpose) {
        var generated = kms.generateDataKey(r -> r.keyId(props.masterKeyAlias()).keySpec(DataKeySpec.AES_256));
        Integer count = jdbc.queryForObject("SELECT count(*) FROM encryption_keys WHERE purpose = ?", Integer.class,
                purpose);
        String id = purpose.substring(0, 1).toLowerCase(Locale.ROOT) + ((count == null ? 0 : count) + 1);
        jdbc.update("""
                INSERT INTO encryption_keys (id, purpose, encrypted_key, active, created_at) VALUES (?, ?, ?, TRUE, ?)
                """, id, purpose, Base64.getEncoder().encodeToString(generated.ciphertextBlob().asByteArray()),
                Timestamp.from(clock.instant()));
        return id;
    }

    private void reload() {
        List<StoredKey> stored = jdbc.query("SELECT id, purpose, encrypted_key, active FROM encryption_keys",
                (rs, i) -> new StoredKey(rs.getString(1), rs.getString(2), rs.getString(3), rs.getBoolean(4)));
        for (StoredKey key : stored) {
            SecretKey secret = keys.computeIfAbsent(key.id(), id -> decrypt(key.encryptedKey()));
            if (key.active() && DATA.equals(key.purpose())) {
                activeDataKeyId = key.id();
            } else if (key.active() && INDEX.equals(key.purpose())) {
                indexKey = secret;
            }
        }
    }

    private SecretKey decrypt(String encrypted) {
        byte[] blob = Base64.getDecoder().decode(encrypted);
        byte[] plaintext = kms.decrypt(r -> r.ciphertextBlob(SdkBytes.fromByteArray(blob))).plaintext().asByteArray();
        return new SecretKeySpec(plaintext, "AES");
    }
}
